# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dict.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='dict.proto',
  package='grpc',
  syntax='proto3',
  serialized_options=b'\n\034org.apache.spark.plugin.grpcB\010DictImplP\001\242\002\004DICT',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\ndict.proto\x12\x04grpc\"\x1c\n\rLookupRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\"\x1b\n\nValueReply\x12\r\n\x05value\x18\x01 \x01(\t29\n\x04\x44ict\x12\x31\n\x06Lookup\x12\x13.grpc.LookupRequest\x1a\x10.grpc.ValueReply\"\x00\x42\x31\n\x1corg.apache.spark.plugin.grpcB\x08\x44ictImplP\x01\xa2\x02\x04\x44ICTb\x06proto3'
)




_LOOKUPREQUEST = _descriptor.Descriptor(
  name='LookupRequest',
  full_name='grpc.LookupRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='grpc.LookupRequest.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=48,
)


_VALUEREPLY = _descriptor.Descriptor(
  name='ValueReply',
  full_name='grpc.ValueReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='grpc.ValueReply.value', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=77,
)

DESCRIPTOR.message_types_by_name['LookupRequest'] = _LOOKUPREQUEST
DESCRIPTOR.message_types_by_name['ValueReply'] = _VALUEREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LookupRequest = _reflection.GeneratedProtocolMessageType('LookupRequest', (_message.Message,), {
  'DESCRIPTOR' : _LOOKUPREQUEST,
  '__module__' : 'dict_pb2'
  # @@protoc_insertion_point(class_scope:grpc.LookupRequest)
  })
_sym_db.RegisterMessage(LookupRequest)

ValueReply = _reflection.GeneratedProtocolMessageType('ValueReply', (_message.Message,), {
  'DESCRIPTOR' : _VALUEREPLY,
  '__module__' : 'dict_pb2'
  # @@protoc_insertion_point(class_scope:grpc.ValueReply)
  })
_sym_db.RegisterMessage(ValueReply)


DESCRIPTOR._options = None

_DICT = _descriptor.ServiceDescriptor(
  name='Dict',
  full_name='grpc.Dict',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=79,
  serialized_end=136,
  methods=[
  _descriptor.MethodDescriptor(
    name='Lookup',
    full_name='grpc.Dict.Lookup',
    index=0,
    containing_service=None,
    input_type=_LOOKUPREQUEST,
    output_type=_VALUEREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_DICT)

DESCRIPTOR.services_by_name['Dict'] = _DICT

# @@protoc_insertion_point(module_scope)
