# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kvs.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='kvs.proto',
  package='grpc',
  syntax='proto3',
  serialized_options=b'\n\034org.apache.spark.plugin.grpcB\rKeyValueStoreP\001\242\002\003KVS',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\tkvs.proto\x12\x04grpc\"\x1c\n\rLookupRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\"\x1b\n\nValueReply\x12\r\n\x05value\x18\x01 \x01(\t2E\n\x10\x41ssociativeArray\x12\x31\n\x06Lookup\x12\x13.grpc.LookupRequest\x1a\x10.grpc.ValueReply\"\x00\x42\x35\n\x1corg.apache.spark.plugin.grpcB\rKeyValueStoreP\x01\xa2\x02\x03KVSb\x06proto3'
)




_LOOKUPREQUEST = _descriptor.Descriptor(
  name='LookupRequest',
  full_name='grpc.LookupRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='grpc.LookupRequest.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=47,
)


_VALUEREPLY = _descriptor.Descriptor(
  name='ValueReply',
  full_name='grpc.ValueReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='grpc.ValueReply.value', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=76,
)

DESCRIPTOR.message_types_by_name['LookupRequest'] = _LOOKUPREQUEST
DESCRIPTOR.message_types_by_name['ValueReply'] = _VALUEREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LookupRequest = _reflection.GeneratedProtocolMessageType('LookupRequest', (_message.Message,), {
  'DESCRIPTOR' : _LOOKUPREQUEST,
  '__module__' : 'kvs_pb2'
  # @@protoc_insertion_point(class_scope:grpc.LookupRequest)
  })
_sym_db.RegisterMessage(LookupRequest)

ValueReply = _reflection.GeneratedProtocolMessageType('ValueReply', (_message.Message,), {
  'DESCRIPTOR' : _VALUEREPLY,
  '__module__' : 'kvs_pb2'
  # @@protoc_insertion_point(class_scope:grpc.ValueReply)
  })
_sym_db.RegisterMessage(ValueReply)


DESCRIPTOR._options = None

_ASSOCIATIVEARRAY = _descriptor.ServiceDescriptor(
  name='AssociativeArray',
  full_name='grpc.AssociativeArray',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=78,
  serialized_end=147,
  methods=[
  _descriptor.MethodDescriptor(
    name='Lookup',
    full_name='grpc.AssociativeArray.Lookup',
    index=0,
    containing_service=None,
    input_type=_LOOKUPREQUEST,
    output_type=_VALUEREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_ASSOCIATIVEARRAY)

DESCRIPTOR.services_by_name['AssociativeArray'] = _ASSOCIATIVEARRAY

# @@protoc_insertion_point(module_scope)
